import Foundation

/// The `INSERT`s the queued added rows become.
///
/// Three rules the source study paid for, enforced here:
///
/// 1. **A column the user did not provide is left out of the statement**, not sent as `NULL`. On
///    PostgreSQL and MySQL an omitted column takes its own default or is generated by the server;
///    writing `NULL` over it either fails on a `NOT NULL` key or quietly overrides the default. A
///    cell whose whole text is `DEFAULT` is the same idea for a column the user *did* touch, and
///    is rendered as the `DEFAULT` keyword, never quoted — and, being a keyword, never bound.
/// 2. **Rows are batched**, one multi-row `VALUES` per batch, bounded by `WriteBatchBudget` on rows,
///    bytes and parameters at once, with the batch closed **before** the row that would cross it.
///    Rows only share a batch when they write the same set of columns, what the study calls grouping
///    by column set.
/// 3. **A row the server fills in entirely is never dropped.** It gets the driver's own all-default
///    form (`INSERT … DEFAULT VALUES`, `INSERT … () VALUES ()`). The study records a generator that
///    returned nothing for such a row and let the rest of the batch commit and report success; that
///    is the bug this type exists to make impossible. Where a driver has no such form (Trino), the
///    plan says the row was not planned instead of emitting SQL the server would refuse.
///
/// The batch is built as one `BoundSQL`, so a driver that binds gets `$1`/`?` and the typed values
/// while a driver that cannot gets the literals — both from the same row list, so the reviewed batch
/// and the run batch cannot disagree about which value is which parameter.
enum InsertStatements {
    /// What the added rows became, and what could not be planned.
    struct Result: Equatable {
        var statements: [WriteStatement] = []
        /// Rows that could not be planned, named. Non-empty is not success with fewer rows; it is
        /// the plan telling the user what it left out.
        var warnings: [String] = []
    }

    /// One cell of an added row: a keyword the server understands, or a value to bind.
    private enum Cell {
        /// `DEFAULT`, a keyword. Never bound and never quoted.
        case keyword(String)
        /// A value, bound when the driver binds.
        case value(BindValue, display: String)

        var display: String {
            switch self {
            case .keyword(let word): word
            case .value(_, let literal): literal
            }
        }
    }

    /// The statements for every added row, in the queue's own order.
    static func build(edits: CellEdits, columns: [Event.Column], table: String,
                      kind: ConnectionKind, budget: WriteBatchBudget) -> Result {
        let style = ParameterStyle.forKind(kind)
        var result = Result()
        // The open batch: the column indices it writes, and one cell list per row.
        var batchColumns: [Int] = []
        var batchRows: [[Cell]] = []

        func insertStatement(columns indices: [Int], rows: [[Cell]]) -> BoundSQL {
            let names = indices.map { quotedIdent(columns[$0].name, for: kind) }
                .joined(separator: ", ")
            var bound = BoundSQL(style: style)
            bound.text("INSERT INTO \(table) (\(names)) VALUES ")
            for (rowIndex, row) in rows.enumerated() {
                if rowIndex > 0 { bound.text(", ") }
                bound.text("(")
                for (cellIndex, cell) in row.enumerated() {
                    if cellIndex > 0 { bound.text(", ") }
                    switch cell {
                    case .keyword(let word):
                        bound.text(word)
                    case .value(let value, let display):
                        bound.value(value, display: display)
                    }
                }
                bound.text(")")
            }
            return bound
        }

        func flush() {
            guard !batchColumns.isEmpty, !batchRows.isEmpty else { return }
            let bound = insertStatement(columns: batchColumns, rows: batchRows)
            result.statements.append(WriteStatement(kind: .insert, bound: bound,
                                                    expectedRows: batchRows.count, keyed: false,
                                                    unmatchedColumns: []))
            batchColumns = []
            batchRows = []
        }

        for insert in edits.inserted.sorted(by: { $0.sequence < $1.sequence }) {
            let indices = insert.values.keys.sorted()
            let cells = indices.map { index -> Cell in
                let text = insert.values[index] ?? ""
                if UpdateStatements.isDefaultKeyword(text) { return .keyword("DEFAULT") }
                let type = columns[index].type
                return .value(BindValue.from(text: text, type: type),
                              display: UpdateStatements.literal(text, type: type))
            }
            let allDefault = cells.allSatisfy { cell in
                if case .keyword = cell { return true }
                return false
            }

            if indices.isEmpty || allDefault {
                // A row with nothing the server does not compute for itself. It is a statement of
                // its own, and it is never silently skipped: the rest of the plan must not commit
                // while reporting success for a row that vanished.
                flush()
                if let sql = allDefaultSQL(table: table, kind: kind) {
                    var bound = BoundSQL(style: style)
                    bound.text(sql)
                    result.statements.append(WriteStatement(kind: .insert, bound: bound,
                                                            expectedRows: 1, keyed: false,
                                                            unmatchedColumns: []))
                } else {
                    result.warnings.append(
                        "added row \(-insert.id) was not planned: \(kind.label) has no all-default "
                        + "INSERT form, so every column would have to be named explicitly")
                }
                continue
            }

            if !batchColumns.isEmpty, batchColumns != indices {
                flush()
            }
            if !batchColumns.isEmpty,
               !fits(existing: batchRows, adding: cells, budget: budget,
                     bound: { insertStatement(columns: indices, rows: $0) }) {
                // Close the batch before the row that would cross a bound; the row starts the next.
                flush()
            }
            if batchColumns.isEmpty { batchColumns = indices }
            batchRows.append(cells)
        }
        flush()
        return result
    }

    /// Whether one more row still fits in the budget. Called before the row is added, so the batch
    /// is closed *before* the row that would cross a bound rather than after it.
    ///
    /// The parameter count is the **bound** count, read off the statement the driver would actually
    /// run, so Trino — which binds nothing — never trips the parameter axis. The byte count is the
    /// display length, which carries the values inline whatever the driver does with them; that is
    /// the same proxy the inline plan always used and it still bounds one request.
    private static func fits(existing: [[Cell]], adding: [Cell], budget: WriteBatchBudget,
                             bound: ([[Cell]]) -> BoundSQL) -> Bool {
        if existing.count + 1 > budget.maxRows { return false }
        let candidate = bound(existing + [adding])
        if candidate.parameters.count > budget.maxParameters { return false }
        return candidate.display.utf8.count <= budget.maxBytes
    }

    /// The driver's form for a row whose every column is the server's to compute, or `nil` when it
    /// has none. Trino fills omitted columns with `NULL` and treats `DEFAULT` as a column name, so
    /// there is no honest form to emit for it.
    static func allDefaultSQL(table: String, kind: ConnectionKind) -> String? {
        switch kind {
        case .postgres: "INSERT INTO \(table) DEFAULT VALUES"
        case .mysql: "INSERT INTO \(table) () VALUES ()"
        case .trino: nil
        }
    }
}
