#!/usr/bin/env python3
"""Generate the dev-fixture SQL for both engines.

    python3 deploy/dev/make_seed.py

Writes deploy/dev/seed-postgres.sql and deploy/dev/seed-mysql.sql. Generated
rather than hand-written because the wide table has 30 columns and 500,000 rows:
thirty hand-typed expressions drift apart the first time one is edited.

The two tables:

* ``wide_500k`` — 500,000 rows by 30 columns of short text. The shape the
  performance targets in the blueprint are stated against.
* ``type_zoo`` — one row per hard type: NUMERIC(38,10) at full precision, an
  offset timestamp, a naive timestamp, interval, json/jsonb, arrays with a NULL
  inside, bytea with a NUL and a non-UTF8 byte, enum labels, uuid, and geometry
  as text. This is the table the golden snapshots cannot cover without a server.

Ids and values are deterministic: running this twice produces byte-identical
files, so a fixture change always shows up as a diff.
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
WIDE_ROWS = 500_000
TEXT_COLUMNS = 29  # plus `id` makes 30


def text_column_names() -> list[str]:
    return [f"c{index:02d}" for index in range(1, TEXT_COLUMNS + 1)]


def postgres_wide() -> str:
    """Build wide_500k in-PL/pgSQL, so the column list is written once."""
    names = text_column_names()
    projected = ",\n    ".join(
        f"'row-' || g || '-{name}' AS {name}" for name in names
    )
    columns = ",\n  ".join(f"{name} text" for name in names)
    return f"""-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS wide_500k;
CREATE TABLE wide_500k (
  id bigint PRIMARY KEY,
  {columns}
);

-- One INSERT ... SELECT rather than 500,000 round trips: generate_series runs
-- on the server, so the fixture load does not measure the client.
INSERT INTO wide_500k
SELECT
    g AS id,
    {projected}
FROM generate_series(1, {WIDE_ROWS}) AS g;

ANALYZE wide_500k;
"""


def postgres_type_zoo() -> str:
    return """-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS type_zoo;
DROP TYPE IF EXISTS mood;

CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

CREATE TABLE type_zoo (
  id            integer PRIMARY KEY,
  exact_money   numeric(38,10),
  tiny_negative numeric(38,10),
  tz_aware      timestamptz,
  tz_naive      timestamp,
  a_date        date,
  a_time        time,
  an_interval   interval,
  a_json        json,
  a_jsonb       jsonb,
  ints          integer[],
  texts         text[],
  nested        integer[][],
  raw_bytes     bytea,
  a_uuid        uuid,
  a_mood        mood,
  a_point       point,
  no_value      text,
  empty_text    text,
  the_word_null text
);

INSERT INTO type_zoo VALUES (
  1,
  1234567890123456789012345678.1234567890,
  -0.0000000001,
  -- A non-UTC offset on purpose: normalising to UTC is what loses the +07:00
  -- the user asked the database for.
  TIMESTAMPTZ '2026-01-31 12:00:00.123456+07',
  TIMESTAMP   '2026-01-31 12:00:00.123456',
  DATE        '2026-01-31',
  TIME        '23:59:59.999999',
  INTERVAL    '1 year 2 mons 3 days 04:05:06',
  '{"b": 1, "a": 2}'::json,
  '{"b": 1, "a": 2}'::jsonb,
  ARRAY[1, NULL, 3],
  ARRAY['a', NULL, 'c'],
  ARRAY[ARRAY[1, 2], ARRAY[3, NULL]],
  -- A NUL and 0xFF: neither is valid UTF-8, so a lossy decode would replace
  -- real bytes with a replacement character.
  '\\x0001ff'::bytea,
  '550e8400-e29b-41d4-a716-446655440000'::uuid,
  'ok'::mood,
  point(1, 2),
  NULL,
  '',
  'NULL'
);
"""


def mysql_wide() -> str:
    names = text_column_names()
    columns = ",\n  ".join(f"{name} text" for name in names)
    projected = ",\n      ".join(
        f"CONCAT('row-', n, '-{name}')" for name in names
    )
    return f"""-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS wide_500k;
CREATE TABLE wide_500k (
  id bigint NOT NULL PRIMARY KEY,
  {columns}
) ENGINE=InnoDB;

-- MySQL has no generate_series. The default recursion cap is 1000, which would
-- silently stop the fixture at 1000 rows, so it is raised for this session.
SET SESSION cte_max_recursion_depth = {WIDE_ROWS + 1000};

INSERT INTO wide_500k
WITH RECURSIVE seq (n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < {WIDE_ROWS}
)
SELECT
      n,
      {projected}
FROM seq;

ANALYZE TABLE wide_500k;
"""


def mysql_type_zoo() -> str:
    return """-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS type_zoo;

CREATE TABLE type_zoo (
  id            int NOT NULL PRIMARY KEY,
  exact_money   decimal(38,10),
  tiny_negative decimal(38,10),
  a_datetime    datetime(6),
  a_timestamp   timestamp(6) NULL,
  a_date        date,
  a_time        time(6),
  a_json        json,
  raw_bytes     blob,
  a_enum        enum('sad','ok','happy'),
  a_char_uuid   char(36),
  a_binary_uuid binary(16),
  no_value      text,
  empty_text    text,
  the_word_null text
) ENGINE=InnoDB;

INSERT INTO type_zoo VALUES (
  1,
  1234567890123456789012345678.1234567890,
  -0.0000000001,
  -- DATETIME keeps the wall clock the client sent; TIMESTAMP converts it to the
  -- session time zone. That difference is deliberate and must stay visible, so
  -- the session is pinned off UTC here.
  '2026-01-31 12:00:00.123456',
  '2026-01-31 12:00:00.123456',
  '2026-01-31',
  '23:59:59.999999',
  '{"b": 1, "a": 2}',
  X'0001FF',
  'ok',
  '550e8400-e29b-41d4-a716-446655440000',
  UNHEX(REPLACE('550e8400-e29b-41d4-a716-446655440000', '-', '')),
  NULL,
  '',
  'NULL'
);

SET SESSION time_zone = '+07:00';
"""


def main() -> int:
    (ROOT / "seed-postgres.sql").write_text(
        postgres_wide() + "\n" + postgres_type_zoo(), encoding="utf-8"
    )
    (ROOT / "seed-mysql.sql").write_text(
        mysql_wide() + "\n" + mysql_type_zoo(), encoding="utf-8"
    )
    print("wrote seed-postgres.sql and seed-mysql.sql")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
