-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS wide_500k;
CREATE TABLE wide_500k (
  id bigint NOT NULL PRIMARY KEY,
  c01 text,
  c02 text,
  c03 text,
  c04 text,
  c05 text,
  c06 text,
  c07 text,
  c08 text,
  c09 text,
  c10 text,
  c11 text,
  c12 text,
  c13 text,
  c14 text,
  c15 text,
  c16 text,
  c17 text,
  c18 text,
  c19 text,
  c20 text,
  c21 text,
  c22 text,
  c23 text,
  c24 text,
  c25 text,
  c26 text,
  c27 text,
  c28 text,
  c29 text
) ENGINE=InnoDB;

-- MySQL has no generate_series. The default recursion cap is 1000, which would
-- silently stop the fixture at 1000 rows, so it is raised for this session.
SET SESSION cte_max_recursion_depth = 501000;

INSERT INTO wide_500k
WITH RECURSIVE seq (n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 500000
)
SELECT
      n,
      CONCAT('row-', n, '-c01'),
      CONCAT('row-', n, '-c02'),
      CONCAT('row-', n, '-c03'),
      CONCAT('row-', n, '-c04'),
      CONCAT('row-', n, '-c05'),
      CONCAT('row-', n, '-c06'),
      CONCAT('row-', n, '-c07'),
      CONCAT('row-', n, '-c08'),
      CONCAT('row-', n, '-c09'),
      CONCAT('row-', n, '-c10'),
      CONCAT('row-', n, '-c11'),
      CONCAT('row-', n, '-c12'),
      CONCAT('row-', n, '-c13'),
      CONCAT('row-', n, '-c14'),
      CONCAT('row-', n, '-c15'),
      CONCAT('row-', n, '-c16'),
      CONCAT('row-', n, '-c17'),
      CONCAT('row-', n, '-c18'),
      CONCAT('row-', n, '-c19'),
      CONCAT('row-', n, '-c20'),
      CONCAT('row-', n, '-c21'),
      CONCAT('row-', n, '-c22'),
      CONCAT('row-', n, '-c23'),
      CONCAT('row-', n, '-c24'),
      CONCAT('row-', n, '-c25'),
      CONCAT('row-', n, '-c26'),
      CONCAT('row-', n, '-c27'),
      CONCAT('row-', n, '-c28'),
      CONCAT('row-', n, '-c29')
FROM seq;

ANALYZE TABLE wide_500k;

-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS type_zoo;

CREATE TABLE type_zoo (
  id            int NOT NULL PRIMARY KEY,
  exact_money   decimal(38,10),
  tiny_negative decimal(38,10),
  a_datetime    datetime(6),
  a_timestamp   timestamp(6) NULL,
  a_date        date,
  a_time        time(6),
  a_json        json,
  raw_bytes     blob,
  a_enum        enum('sad','ok','happy'),
  a_char_uuid   char(36),
  a_binary_uuid binary(16),
  no_value      text,
  empty_text    text,
  the_word_null text
) ENGINE=InnoDB;

INSERT INTO type_zoo VALUES (
  1,
  1234567890123456789012345678.1234567890,
  -0.0000000001,
  -- DATETIME keeps the wall clock the client sent; TIMESTAMP converts it to the
  -- session time zone. That difference is deliberate and must stay visible, so
  -- the session is pinned off UTC here.
  '2026-01-31 12:00:00.123456',
  '2026-01-31 12:00:00.123456',
  '2026-01-31',
  '23:59:59.999999',
  '{"b": 1, "a": 2}',
  X'0001FF',
  'ok',
  '550e8400-e29b-41d4-a716-446655440000',
  UNHEX(REPLACE('550e8400-e29b-41d4-a716-446655440000', '-', '')),
  NULL,
  '',
  'NULL'
);

SET SESSION time_zone = '+07:00';
