-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS wide_500k;
CREATE TABLE wide_500k (
  id bigint PRIMARY KEY,
  c01 text,
  c02 text,
  c03 text,
  c04 text,
  c05 text,
  c06 text,
  c07 text,
  c08 text,
  c09 text,
  c10 text,
  c11 text,
  c12 text,
  c13 text,
  c14 text,
  c15 text,
  c16 text,
  c17 text,
  c18 text,
  c19 text,
  c20 text,
  c21 text,
  c22 text,
  c23 text,
  c24 text,
  c25 text,
  c26 text,
  c27 text,
  c28 text,
  c29 text
);

-- One INSERT ... SELECT rather than 500,000 round trips: generate_series runs
-- on the server, so the fixture load does not measure the client.
INSERT INTO wide_500k
SELECT
    g AS id,
    'row-' || g || '-c01' AS c01,
    'row-' || g || '-c02' AS c02,
    'row-' || g || '-c03' AS c03,
    'row-' || g || '-c04' AS c04,
    'row-' || g || '-c05' AS c05,
    'row-' || g || '-c06' AS c06,
    'row-' || g || '-c07' AS c07,
    'row-' || g || '-c08' AS c08,
    'row-' || g || '-c09' AS c09,
    'row-' || g || '-c10' AS c10,
    'row-' || g || '-c11' AS c11,
    'row-' || g || '-c12' AS c12,
    'row-' || g || '-c13' AS c13,
    'row-' || g || '-c14' AS c14,
    'row-' || g || '-c15' AS c15,
    'row-' || g || '-c16' AS c16,
    'row-' || g || '-c17' AS c17,
    'row-' || g || '-c18' AS c18,
    'row-' || g || '-c19' AS c19,
    'row-' || g || '-c20' AS c20,
    'row-' || g || '-c21' AS c21,
    'row-' || g || '-c22' AS c22,
    'row-' || g || '-c23' AS c23,
    'row-' || g || '-c24' AS c24,
    'row-' || g || '-c25' AS c25,
    'row-' || g || '-c26' AS c26,
    'row-' || g || '-c27' AS c27,
    'row-' || g || '-c28' AS c28,
    'row-' || g || '-c29' AS c29
FROM generate_series(1, 500000) AS g;

ANALYZE wide_500k;

-- generated by deploy/dev/make_seed.py -- do not edit by hand
DROP TABLE IF EXISTS type_zoo;
DROP TYPE IF EXISTS mood;

CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

CREATE TABLE type_zoo (
  id            integer PRIMARY KEY,
  exact_money   numeric(38,10),
  tiny_negative numeric(38,10),
  tz_aware      timestamptz,
  tz_naive      timestamp,
  a_date        date,
  a_time        time,
  an_interval   interval,
  a_json        json,
  a_jsonb       jsonb,
  ints          integer[],
  texts         text[],
  nested        integer[][],
  raw_bytes     bytea,
  a_uuid        uuid,
  a_mood        mood,
  a_point       point,
  no_value      text,
  empty_text    text,
  the_word_null text
);

INSERT INTO type_zoo VALUES (
  1,
  1234567890123456789012345678.1234567890,
  -0.0000000001,
  -- A non-UTC offset on purpose: normalising to UTC is what loses the +07:00
  -- the user asked the database for.
  TIMESTAMPTZ '2026-01-31 12:00:00.123456+07',
  TIMESTAMP   '2026-01-31 12:00:00.123456',
  DATE        '2026-01-31',
  TIME        '23:59:59.999999',
  INTERVAL    '1 year 2 mons 3 days 04:05:06',
  '{"b": 1, "a": 2}'::json,
  '{"b": 1, "a": 2}'::jsonb,
  ARRAY[1, NULL, 3],
  ARRAY['a', NULL, 'c'],
  ARRAY[ARRAY[1, 2], ARRAY[3, NULL]],
  -- A NUL and 0xFF: neither is valid UTF-8, so a lossy decode would replace
  -- real bytes with a replacement character.
  '\x0001ff'::bytea,
  '550e8400-e29b-41d4-a716-446655440000'::uuid,
  'ok'::mood,
  point(1, 2),
  NULL,
  '',
  'NULL'
);
