#!/bin/bash
# Regenerates Sources/TrinoExporter/Support/DriverLogos.swift from assets/drivers/*.svg.
#
#   ./app/make-driver-logos.sh
#
# The brand marks are the one piece of this app that is not our artwork, so they stay as real
# .svg files in the repository — reviewable, replaceable, and attributable — and the Swift that
# carries them into the UI is generated from those rather than pasted in by hand.
set -euo pipefail
cd "$(dirname "$0")"

OUT="Sources/TrinoExporter/Support/DriverLogos.swift"
SRC="../assets/drivers"

{
  cat <<'HEADER'
// Generated by app/make-driver-logos.sh from assets/drivers/*.svg. Do not edit by hand.
//
// The three marks come from simple-icons (CC0-1.0). Each logo is a trademark of its project and
// is used here only to say which database a connection speaks to — the same use every database
// client makes of them. See assets/drivers/README.md.

import AppKit

enum DriverLogo {
    private static var cache: [ConnectionKind: NSImage] = [:]

    /// The driver's brand mark, ready to sit on a coloured tile. `NSImage` decodes SVG on
    /// macOS 14, so this needs no rasterising step and stays sharp at every size the UI asks for.
    static func image(for kind: ConnectionKind) -> NSImage? {
        if let cached = cache[kind] { return cached }
        let data = Data(source(for: kind).utf8)
        guard let image = NSImage(data: data) else { return nil }
        image.isTemplate = false
        cache[kind] = image
        return image
    }

    private static func source(for kind: ConnectionKind) -> String {
        switch kind {
        case .trino: trino
        case .postgres: postgresql
        case .mysql: mysql
        }
    }
HEADER
  # simple-icons paths carry no fill, which means black. The UI draws them on saturated tiles, so
  # white is injected at the root where the path inherits it.
  for pair in "trino:trino" "postgresql:postgresql" "mysql:mysql"; do
    file="${pair%%:*}"; name="${pair##*:}"
    printf '\n    private static let %s = """\n' "$name"
    # Sources disagree about colour: simple-icons leaves the path unfilled (black), devicon
    # hard-codes the brand hue. Both are stripped here and white injected once at the root, so a
    # file can be swapped without touching this script. `fill="none"` survives — those are
    # cut-outs, and filling them would turn a hole into a blob.
    #
    # Then indented to match the closing delimiter: Swift requires every line of a multi-line
    # literal to reach at least as far as the delimiter that ends it.
    sed -E -e 's/ fill="#[0-9A-Fa-f]{3,8}"//g' -e 's|<svg |<svg fill="#FFFFFF" |' -e 's|^|    |' "$SRC/$file.svg"
    # The .svg files carry no trailing newline, and a multi-line literal's closing delimiter has
    # to start a line of its own.
    printf '\n    """\n'
  done
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
