import Foundation

/// The `INSERT`s the queued added rows become.
///
/// Three rules the source study paid for, enforced here:
///
/// 1. **A column the user did not provide is left out of the statement**, not sent as `NULL`. On
///    PostgreSQL and MySQL an omitted column takes its own default or is generated by the server;
///    writing `NULL` over it either fails on a `NOT NULL` key or quietly overrides the default. A
///    cell whose whole text is `DEFAULT` is the same idea for a column the user *did* touch, and
///    is rendered as the `DEFAULT` keyword, never quoted.
/// 2. **Rows are batched**, one multi-row `VALUES` per batch, bounded by `WriteBatchBudget` on rows,
///    bytes and parameters at once, with the batch closed **before** the row that would cross it.
///    Rows only share a batch when they write the same set of columns, what the study calls grouping
///    by column set.
/// 3. **A row the server fills in entirely is never dropped.** It gets the driver's own all-default
///    form (`INSERT … DEFAULT VALUES`, `INSERT … () VALUES ()`). The study records a generator that
///    returned nothing for such a row and let the rest of the batch commit and report success; that
///    is the bug this type exists to make impossible. Where a driver has no such form (Trino), the
///    plan says the row was not planned instead of emitting SQL the server would refuse.
enum InsertStatements {
    /// What the added rows became, and what could not be planned.
    struct Result: Equatable {
        var statements: [WriteStatement] = []
        /// Rows that could not be planned, named. Non-empty is not success with fewer rows; it is
        /// the plan telling the user what it left out.
        var warnings: [String] = []
    }

    /// The statements for every added row, in the queue's own order.
    static func build(edits: CellEdits, columns: [Event.Column], table: String,
                      kind: ConnectionKind, budget: WriteBatchBudget) -> Result {
        var result = Result()
        // The open batch: the column indices it writes, and one expression list per row.
        var batchColumns: [Int] = []
        var batchValues: [[String]] = []

        func insertSQL(columns indices: [Int], values: [[String]]) -> String {
            let names = indices.map { quotedIdent(columns[$0].name, for: kind) }
                .joined(separator: ", ")
            let rows = values.map { "(" + $0.joined(separator: ", ") + ")" }
                .joined(separator: ", ")
            return "INSERT INTO \(table) (\(names)) VALUES \(rows)"
        }

        func flush() {
            guard !batchColumns.isEmpty, !batchValues.isEmpty else { return }
            let sql = insertSQL(columns: batchColumns, values: batchValues)
            result.statements.append(WriteStatement(kind: .insert, sql: sql,
                                                    expectedRows: batchValues.count, keyed: false,
                                                    unmatchedColumns: []))
            batchColumns = []
            batchValues = []
        }

        for insert in edits.inserted.sorted(by: { $0.sequence < $1.sequence }) {
            let indices = insert.values.keys.sorted()
            let expressions = indices.map { index -> String in
                let text = insert.values[index] ?? ""
                return UpdateStatements.isDefaultKeyword(text)
                    ? "DEFAULT"
                    : UpdateStatements.literal(text, type: columns[index].type)
            }
            let allDefault = expressions.allSatisfy { $0 == "DEFAULT" }

            if indices.isEmpty || allDefault {
                // A row with nothing the server does not compute for itself. It is a statement of
                // its own, and it is never silently skipped: the rest of the plan must not commit
                // while reporting success for a row that vanished.
                flush()
                if let sql = allDefaultSQL(table: table, kind: kind) {
                    result.statements.append(WriteStatement(kind: .insert, sql: sql, expectedRows: 1,
                                                            keyed: false, unmatchedColumns: []))
                } else {
                    result.warnings.append(
                        "added row \(-insert.id) was not planned: \(kind.label) has no all-default "
                        + "INSERT form, so every column would have to be named explicitly")
                }
                continue
            }

            if !batchColumns.isEmpty, batchColumns != indices {
                flush()
            }
            if !batchColumns.isEmpty,
               !fits(existing: batchValues, adding: expressions, budget: budget,
                     sql: { insertSQL(columns: indices, values: $0) }) {
                // Close the batch before the row that would cross a bound; the row starts the next.
                flush()
            }
            if batchColumns.isEmpty { batchColumns = indices }
            batchValues.append(expressions)
        }
        flush()
        return result
    }

    /// Whether one more row still fits in the budget. Called before the row is added, so the batch
    /// is closed *before* the row that would cross a bound rather than after it.
    private static func fits(existing: [[String]], adding: [String], budget: WriteBatchBudget,
                             sql: ([[String]]) -> String) -> Bool {
        if existing.count + 1 > budget.maxRows { return false }
        let parameters = (existing + [adding]).reduce(0) { $0 + $1.count }
        if parameters > budget.maxParameters { return false }
        return sql(existing + [adding]).utf8.count <= budget.maxBytes
    }

    /// The driver's form for a row whose every column is the server's to compute, or `nil` when it
    /// has none. Trino fills omitted columns with `NULL` and treats `DEFAULT` as a column name, so
    /// there is no honest form to emit for it.
    static func allDefaultSQL(table: String, kind: ConnectionKind) -> String? {
        switch kind {
        case .postgres: "INSERT INTO \(table) DEFAULT VALUES"
        case .mysql: "INSERT INTO \(table) () VALUES ()"
        case .trino: nil
        }
    }
}
