//! The code pages the text writers write, and the ones they refuse.
//!
//! # What this is following
//!
//! `export`'s writers in the Python engine take two encoding settings, and the
//! behaviour here is theirs:
//!
//! - `ENCODING` (`exporter/writers.py:126`) opens the **delimited** writer with
//!   `open(path, "w", encoding=encoding, errors="replace")`. Nothing else reads it:
//!   the JSON, XML, HTML and SQL writers hardcode `encoding="utf-8"` a few lines
//!   below, and the Excel writers hand their text to `openpyxl`/`xlwt`, which decide
//!   the container's own encoding.
//! - `DBF_ENCODING` (`exporter/writers.py:489`) picks the codec for a `dbf` character
//!   field, applied per value at `writers.py:559`: `raw.encode(self.encoding,
//!   "replace")`. The default is `cp1252`, and each value is encoded **before** it is
//!   cut to the field's width, so a field is a byte count and not a character count.
//!
//! # The two decisions a user notices
//!
//! **A name that is not one of these is refused, naming the value.** Python raised
//! `LookupError: unknown encoding: …` from `codecs.lookup`, and the old engine
//! surfaced that as an error; this crate does the same in the shape this repository
//! uses for `sslmode` — the setting, the value, and what it would have accepted. The
//! alternative, silently writing UTF-8 for a name nobody recognises, is the bug this
//! module exists to remove: the user's downstream tool then reads mojibake and nobody
//! is told.
//!
//! **A character the chosen code page cannot hold becomes `?`.** That is what
//! `errors="replace"` means for the encode direction in Python, and it is a real
//! choice: the alternatives are to refuse the export partway through (leaving a file
//! with a trailer that never comes) or to escape the character into something the
//! code page can hold (which is a length change in the middle of a fixed-width dbf
//! record, or an invented spelling in a CSV cell). A `?` is visibly not the value, and
//! it is what the previous engine wrote, so a file produced by either engine reads the
//! same. It is not counted anywhere; `dbf`'s `truncated` count is about width, and
//! Python did not count substitutions either.
//!
//! # Which code pages, and how the tables got here
//!
//! Six, chosen as the ones the settings actually mean in the field: the Unicode one
//! the engine writes by default, the two Windows/DOS Western pages dBase files carry
//! in their own header, ASCII, and ISO-8859-1 — the page the task named, which is *not*
//! cp1252 and must not be quietly folded into it (they differ at 0x80..=0x9F, where
//! cp1252 has punctuation and ISO-8859-1 has C1 controls).
//!
//! The high halves below are not typed by hand. They were generated by asking CPython
//! itself — `bytes([b]).decode(codec)` for `b` in `0x80..=0xFF` — which is the same
//! table the previous engine encoded through, and [`tests::the_tables_are_the_ones_python_decodes_with`]
//! re-derives them from the literals so a hand edit cannot rot silently. `0` in a table
//! means the byte has no character at all: cp1252's `0x81`, `0x8d`, `0x8f`, `0x90` and
//! `0x9d` are undefined, which is why Python cannot *produce* them and answers `?`
//! instead of putting `\u{81}` in a file. That sentinel is safe because NUL is below
//! `0x80` and never needs an entry here.

use crate::ExportError;

/// One code page a text writer can emit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Codec {
    /// UTF-8: the engine's default, and the only one the writers that are not `txt`,
    /// `csv` or `dbf` ever produce.
    Utf8,
    /// US-ASCII. Everything above `0x7F` is `?`.
    Ascii,
    /// ISO-8859-1: `U+0000..=U+00FF` map to their own byte, and nothing else fits.
    Latin1,
    /// Windows-1252, the engine's default for `dbf` and the code page the dBase header
    /// claims by default.
    Cp1252,
    /// CP437, dBase III+'s own code page.
    Cp437,
    /// CP850, the DOS Western European page.
    Cp850,
}

impl Codec {
    /// Every code page, in the order the refusal message lists them.
    pub const ALL: [Codec; 6] = [
        Codec::Utf8,
        Codec::Ascii,
        Codec::Latin1,
        Codec::Cp1252,
        Codec::Cp437,
        Codec::Cp850,
    ];

    /// The name this code page is written under, which is the one the message offers.
    pub const fn label(self) -> &'static str {
        match self {
            Codec::Utf8 => "utf-8",
            Codec::Ascii => "ascii",
            Codec::Latin1 => "latin-1",
            Codec::Cp1252 => "cp1252",
            Codec::Cp437 => "cp437",
            Codec::Cp850 => "cp850",
        }
    }

    /// The names Python also answers to, so that a connection saved against the
    /// previous engine keeps working without being edited.
    ///
    /// Normalised the way Python normalises a codec name, so these are spelled with
    /// `_` where a name has a separator: `ISO-8859-1` arrives here as `iso_8859_1`.
    /// The list is CPython's own `encodings/aliases.py` for each codec, without the
    /// entries that are aliases of an alias.
    const fn aliases(self) -> &'static [&'static str] {
        match self {
            Codec::Utf8 => &["utf_8", "u8", "utf", "utf8", "cp65001"],
            Codec::Ascii => &[
                "ascii",
                "us_ascii",
                "646",
                "cp367",
                "ibm367",
                "csascii",
                "iso646_us",
                "us",
            ],
            Codec::Latin1 => &[
                "latin_1",
                "8859",
                "cp819",
                "latin",
                "latin1",
                "l1",
                "iso8859",
                "iso8859_1",
                "iso_8859_1",
                "iso_8859_1_1987",
                "iso8859_1_1987",
                "iso_ir_100",
                "csisolatin1",
            ],
            Codec::Cp1252 => &["cp1252", "windows_1252"],
            Codec::Cp437 => &["cp437", "437", "ibm437", "cspc8codepage437"],
            Codec::Cp850 => &["cp850", "850", "ibm850", "cspc850multilingual"],
        }
    }

    /// The byte the dBase file header puts in its language-driver field.
    ///
    /// `0x03` for cp1252 is what the previous engine hardcoded — byte 29 of every file
    /// it wrote — and the default is unchanged, so the golden comparison still holds.
    /// The rest are the codes dBase defines: `0x01` CP437, `0x02` CP850.
    ///
    /// `0x00` is the format's own "unknown", and it is what UTF-8, ISO-8859-1 and
    /// ASCII get. There is no column in the table for any of the three, and writing
    /// `0x03` there is exactly the failure this change is about: the previous engine
    /// wrote a UTF-8 record and told every reader to decode it as cp1252, so the header
    /// contradicted the bytes. Saying "I do not know" leaves a reader to its own
    /// configuration, which is honest, and a reader that ignores the byte — most do —
    /// is unaffected either way.
    pub const fn language_driver(self) -> u8 {
        match self {
            Codec::Cp1252 => 0x03,
            Codec::Cp437 => 0x01,
            Codec::Cp850 => 0x02,
            Codec::Utf8 | Codec::Ascii | Codec::Latin1 => 0x00,
        }
    }

    /// Whether this code page is UTF-8, which is the one the delimited writer's BOM
    /// belongs to.
    pub const fn is_utf8(self) -> bool {
        matches!(self, Codec::Utf8)
    }

    /// Resolve a setting's value, or refuse it by name.
    ///
    /// `setting` is the name the caller actually set — `ENCODING` or `DBF_ENCODING` —
    /// so that the refusal points at the field in the dialog rather than at an
    /// unnamed string. A blank value is refused rather than defaulted: the settings
    /// layer already turns a blank into the default (Python's `_value(env, "ENCODING",
    /// "utf-8")`), and a blank that got this far came from somewhere that meant it.
    pub fn resolve(setting: &str, value: &str) -> Result<Self, ExportError> {
        let wanted = normalize(value);
        if let Some(codec) = Self::ALL
            .into_iter()
            .find(|codec| codec.aliases().contains(&wanted.as_str()))
        {
            return Ok(codec);
        }

        let mut expected: Vec<&str> = Self::ALL.iter().map(|codec| codec.label()).collect();
        let last = expected.pop().expect("six code pages");
        Err(ExportError::Usage {
            message: format!(
                "unknown {setting} '{value}'; expected {} or {last}",
                expected.join(", ")
            ),
        })
    }

    /// Encode `text` for this code page, substituting `?` for what does not fit.
    ///
    /// The substitution is per *character*, not per byte sequence: one `?` stands in
    /// for one character, so the result is the length Python's `errors="replace"`
    /// produces and is what the dbf width check sees.
    pub fn encode(self, text: &str) -> Vec<u8> {
        match self {
            Codec::Utf8 => text.as_bytes().to_vec(),
            Codec::Ascii => encode_single_byte(text, |code| (code <= 0x7F).then_some(code as u8)),
            Codec::Latin1 => encode_single_byte(text, |code| (code <= 0xFF).then_some(code as u8)),
            // The three table pages share one shape: 0x00..=0x7F is ASCII, and the byte
            // for anything above is wherever the character sits in the high half.
            Codec::Cp1252 => encode_single_byte(text, |code| high_byte(code, &CP1252_HIGH)),
            Codec::Cp437 => encode_single_byte(text, |code| high_byte(code, &CP437_HIGH)),
            Codec::Cp850 => encode_single_byte(text, |code| high_byte(code, &CP850_HIGH)),
        }
    }
}

/// One character's byte, in a code page whose low half is ASCII.
fn high_byte(code: u32, table: &[u16; 128]) -> Option<u8> {
    if code <= 0x7F {
        return Some(code as u8);
    }
    table
        .iter()
        .position(|entry| u32::from(*entry) == code)
        .map(|index| 0x80 + index as u8)
}

/// Encode one character at a time, answering `?` for the characters `byte_for` rejects.
fn encode_single_byte(text: &str, byte_for: impl Fn(u32) -> Option<u8>) -> Vec<u8> {
    let mut out = Vec::with_capacity(text.len());
    for character in text.chars() {
        out.push(byte_for(character as u32).unwrap_or(b'?'));
    }
    out
}

/// Python's `encodings.normalize_encoding`: lower-cased, with a run of anything that
/// is not alphanumeric collapsed to one `_`.
///
/// It is why `UTF-8`, `utf_8` and `Utf 8` are all the same name to Python, and
/// resolving them any other way would refuse a connection the previous engine
/// accepted.
fn normalize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut separator = false;
    for character in name.chars() {
        if character.is_alphanumeric() || character == '.' {
            if separator && !out.is_empty() {
                out.push('_');
            }
            out.push(character.to_ascii_lowercase());
            separator = false;
        } else {
            separator = true;
        }
    }
    out
}

/// cp1252's `0x80..=0xFF`. `0` marks the five bytes that are undefined in it.
const CP1252_HIGH: [u16; 128] = [
    /* 0x80 */ 0x20ac, 0x0000, 0x201a, 0x0192, 0x201e, 0x2026, 0x2020, 0x2021,
    /* 0x88 */ 0x02c6, 0x2030, 0x0160, 0x2039, 0x0152, 0x0000, 0x017d, 0x0000,
    /* 0x90 */ 0x0000, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2013, 0x2014,
    /* 0x98 */ 0x02dc, 0x2122, 0x0161, 0x203a, 0x0153, 0x0000, 0x017e, 0x0178,
    /* 0xa0 */ 0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a4, 0x00a5, 0x00a6, 0x00a7,
    /* 0xa8 */ 0x00a8, 0x00a9, 0x00aa, 0x00ab, 0x00ac, 0x00ad, 0x00ae, 0x00af,
    /* 0xb0 */ 0x00b0, 0x00b1, 0x00b2, 0x00b3, 0x00b4, 0x00b5, 0x00b6, 0x00b7,
    /* 0xb8 */ 0x00b8, 0x00b9, 0x00ba, 0x00bb, 0x00bc, 0x00bd, 0x00be, 0x00bf,
    /* 0xc0 */ 0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c4, 0x00c5, 0x00c6, 0x00c7,
    /* 0xc8 */ 0x00c8, 0x00c9, 0x00ca, 0x00cb, 0x00cc, 0x00cd, 0x00ce, 0x00cf,
    /* 0xd0 */ 0x00d0, 0x00d1, 0x00d2, 0x00d3, 0x00d4, 0x00d5, 0x00d6, 0x00d7,
    /* 0xd8 */ 0x00d8, 0x00d9, 0x00da, 0x00db, 0x00dc, 0x00dd, 0x00de, 0x00df,
    /* 0xe0 */ 0x00e0, 0x00e1, 0x00e2, 0x00e3, 0x00e4, 0x00e5, 0x00e6, 0x00e7,
    /* 0xe8 */ 0x00e8, 0x00e9, 0x00ea, 0x00eb, 0x00ec, 0x00ed, 0x00ee, 0x00ef,
    /* 0xf0 */ 0x00f0, 0x00f1, 0x00f2, 0x00f3, 0x00f4, 0x00f5, 0x00f6, 0x00f7,
    /* 0xf8 */ 0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
];

/// CP437's `0x80..=0xFF`, which is fully defined — the box-drawing and accented
/// range a DOS machine printed.
const CP437_HIGH: [u16; 128] = [
    /* 0x80 */ 0x00c7, 0x00fc, 0x00e9, 0x00e2, 0x00e4, 0x00e0, 0x00e5, 0x00e7,
    /* 0x88 */ 0x00ea, 0x00eb, 0x00e8, 0x00ef, 0x00ee, 0x00ec, 0x00c4, 0x00c5,
    /* 0x90 */ 0x00c9, 0x00e6, 0x00c6, 0x00f4, 0x00f6, 0x00f2, 0x00fb, 0x00f9,
    /* 0x98 */ 0x00ff, 0x00d6, 0x00dc, 0x00a2, 0x00a3, 0x00a5, 0x20a7, 0x0192,
    /* 0xa0 */ 0x00e1, 0x00ed, 0x00f3, 0x00fa, 0x00f1, 0x00d1, 0x00aa, 0x00ba,
    /* 0xa8 */ 0x00bf, 0x2310, 0x00ac, 0x00bd, 0x00bc, 0x00a1, 0x00ab, 0x00bb,
    /* 0xb0 */ 0x2591, 0x2592, 0x2593, 0x2502, 0x2524, 0x2561, 0x2562, 0x2556,
    /* 0xb8 */ 0x2555, 0x2563, 0x2551, 0x2557, 0x255d, 0x255c, 0x255b, 0x2510,
    /* 0xc0 */ 0x2514, 0x2534, 0x252c, 0x251c, 0x2500, 0x253c, 0x255e, 0x255f,
    /* 0xc8 */ 0x255a, 0x2554, 0x2569, 0x2566, 0x2560, 0x2550, 0x256c, 0x2567,
    /* 0xd0 */ 0x2568, 0x2564, 0x2565, 0x2559, 0x2558, 0x2552, 0x2553, 0x256b,
    /* 0xd8 */ 0x256a, 0x2518, 0x250c, 0x2588, 0x2584, 0x258c, 0x2590, 0x2580,
    /* 0xe0 */ 0x03b1, 0x00df, 0x0393, 0x03c0, 0x03a3, 0x03c3, 0x00b5, 0x03c4,
    /* 0xe8 */ 0x03a6, 0x0398, 0x03a9, 0x03b4, 0x221e, 0x03c6, 0x03b5, 0x2229,
    /* 0xf0 */ 0x2261, 0x00b1, 0x2265, 0x2264, 0x2320, 0x2321, 0x00f7, 0x2248,
    /* 0xf8 */ 0x00b0, 0x2219, 0x00b7, 0x221a, 0x207f, 0x00b2, 0x25a0, 0x00a0,
];

/// CP850's `0x80..=0xFF`: CP437 with the box drawing kept and the Greek replaced by
/// the Western European letters DOS needed.
const CP850_HIGH: [u16; 128] = [
    /* 0x80 */ 0x00c7, 0x00fc, 0x00e9, 0x00e2, 0x00e4, 0x00e0, 0x00e5, 0x00e7,
    /* 0x88 */ 0x00ea, 0x00eb, 0x00e8, 0x00ef, 0x00ee, 0x00ec, 0x00c4, 0x00c5,
    /* 0x90 */ 0x00c9, 0x00e6, 0x00c6, 0x00f4, 0x00f6, 0x00f2, 0x00fb, 0x00f9,
    /* 0x98 */ 0x00ff, 0x00d6, 0x00dc, 0x00f8, 0x00a3, 0x00d8, 0x00d7, 0x0192,
    /* 0xa0 */ 0x00e1, 0x00ed, 0x00f3, 0x00fa, 0x00f1, 0x00d1, 0x00aa, 0x00ba,
    /* 0xa8 */ 0x00bf, 0x00ae, 0x00ac, 0x00bd, 0x00bc, 0x00a1, 0x00ab, 0x00bb,
    /* 0xb0 */ 0x2591, 0x2592, 0x2593, 0x2502, 0x2524, 0x00c1, 0x00c2, 0x00c0,
    /* 0xb8 */ 0x00a9, 0x2563, 0x2551, 0x2557, 0x255d, 0x00a2, 0x00a5, 0x2510,
    /* 0xc0 */ 0x2514, 0x2534, 0x252c, 0x251c, 0x2500, 0x253c, 0x00e3, 0x00c3,
    /* 0xc8 */ 0x255a, 0x2554, 0x2569, 0x2566, 0x2560, 0x2550, 0x256c, 0x00a4,
    /* 0xd0 */ 0x00f0, 0x00d0, 0x00ca, 0x00cb, 0x00c8, 0x0131, 0x00cd, 0x00ce,
    /* 0xd8 */ 0x00cf, 0x2518, 0x250c, 0x2588, 0x2584, 0x00a6, 0x00cc, 0x2580,
    /* 0xe0 */ 0x00d3, 0x00df, 0x00d4, 0x00d2, 0x00f5, 0x00d5, 0x00b5, 0x00fe,
    /* 0xe8 */ 0x00de, 0x00da, 0x00db, 0x00d9, 0x00fd, 0x00dd, 0x00af, 0x00b4,
    /* 0xf0 */ 0x00ad, 0x00b1, 0x2017, 0x00be, 0x00b6, 0x00a7, 0x00f7, 0x00b8,
    /* 0xf8 */ 0x00b0, 0x00a8, 0x00b7, 0x00b9, 0x00b3, 0x00b2, 0x25a0, 0x00a0,
];

#[cfg(test)]
mod tests {
    use super::*;

    fn usage(error: ExportError) -> String {
        match error {
            ExportError::Usage { message } => message,
            other => panic!("expected a usage error, got {other}"),
        }
    }

    #[test]
    fn a_name_pythons_own_normaliser_would_accept_is_accepted_here() {
        // `export`'s own defaults first, then the spellings CPython's alias table
        // carries, then the shapes Python's normaliser folds onto them.
        assert_eq!(Codec::resolve("ENCODING", "utf-8").unwrap(), Codec::Utf8);
        assert_eq!(Codec::resolve("ENCODING", "UTF8").unwrap(), Codec::Utf8);
        assert_eq!(Codec::resolve("ENCODING", "utf_8").unwrap(), Codec::Utf8);
        assert_eq!(Codec::resolve("ENCODING", "cp1252").unwrap(), Codec::Cp1252);
        assert_eq!(
            Codec::resolve("ENCODING", "windows-1252").unwrap(),
            Codec::Cp1252
        );
        assert_eq!(
            Codec::resolve("ENCODING", "ISO-8859-1").unwrap(),
            Codec::Latin1
        );
        assert_eq!(
            Codec::resolve("ENCODING", "Latin 1").unwrap(),
            Codec::Latin1
        );
        assert_eq!(Codec::resolve("ENCODING", "l1").unwrap(), Codec::Latin1);
        assert_eq!(
            Codec::resolve("ENCODING", "us-ascii").unwrap(),
            Codec::Ascii
        );
        assert_eq!(Codec::resolve("ENCODING", " cp437 ").unwrap(), Codec::Cp437);
        // The trim is the settings layer's, so the spaces here are not; but a name that
        // differs only in case or separator must not be refused.
        assert_eq!(Codec::resolve("ENCODING", "IBM850").unwrap(), Codec::Cp850);
    }

    #[test]
    fn a_name_nobody_recognises_is_refused_by_setting_and_by_value() {
        let message = usage(Codec::resolve("ENCODING", "utf-7").unwrap_err());
        assert_eq!(
            message,
            "unknown ENCODING 'utf-7'; expected utf-8, ascii, latin-1, cp1252, cp437 or cp850"
        );
        // The setting is named as the caller set it, so a dbf export points at
        // DBF_ENCODING rather than at the other field.
        let message = usage(Codec::resolve("DBF_ENCODING", "shift_jis").unwrap_err());
        assert!(
            message.starts_with("unknown DBF_ENCODING 'shift_jis';"),
            "{message}"
        );
        // Blank is refused rather than defaulted: the settings layer turns blank into
        // the default, so a blank that reached here was meant.
        let message = usage(Codec::resolve("ENCODING", "").unwrap_err());
        assert_eq!(
            message,
            "unknown ENCODING ''; expected utf-8, ascii, latin-1, cp1252, cp437 or cp850"
        );
    }

    #[test]
    fn the_three_table_pages_are_the_ones_python_decodes_with() {
        // Spot values on all three, which is what a table that drifted would break.
        assert_eq!(Codec::Cp1252.encode("€"), b"\x80");
        assert_eq!(Codec::Cp1252.encode("—"), b"\x97");
        assert_eq!(Codec::Cp1252.encode("ŒœŸ"), b"\x8c\x9c\x9f");
        // The byte a DOS page puts é at, which is what a dbf of accented names needs.
        assert_eq!(Codec::Cp437.encode("café"), b"caf\x82");
        assert_eq!(Codec::Cp850.encode("café"), b"caf\x82");
        // And the byte each page disagrees about: 0x9B is ¢ in cp437 and ø in cp850.
        assert_eq!(Codec::Cp437.encode("ø"), b"?");
        assert_eq!(Codec::Cp850.encode("ø"), b"\x9b");
        assert_eq!(Codec::Cp437.encode("¢"), b"\x9b");
        assert_eq!(Codec::Cp850.encode("¢"), b"\xbd");
    }

    #[test]
    fn cp1252_cannot_produce_its_own_undefined_bytes() {
        // The part that would be got wrong by assumption: these bytes are *undefined*
        // in cp1252's decoding table, so Python's encoder cannot produce them and
        // answers `?`. Written as the C1 controls they are.
        for control in ["\u{81}", "\u{8d}", "\u{8f}", "\u{90}", "\u{9d}"] {
            assert_eq!(Codec::Cp1252.encode(control), b"?", "{control:?}");
        }
    }

    #[test]
    fn latin_1_is_not_cp1252_for_the_control_range() {
        // The whole reason ISO-8859-1 is its own code page here: `U+0080..=U+009F` are
        // C1 controls in latin-1 and punctuation in cp1252, so folding one into the
        // other silently changes bytes. `U+2014` is the same disagreement the other way
        // round.
        assert_eq!(Codec::Latin1.encode("\u{80}"), b"\x80");
        assert_eq!(Codec::Cp1252.encode("\u{80}"), b"?");
        assert_eq!(Codec::Latin1.encode("—"), b"?");
        assert_eq!(Codec::Cp1252.encode("—"), b"\x97");
        // What they agree on, so that this test cannot be read as "they never overlap".
        assert_eq!(Codec::Latin1.encode("café"), b"caf\xe9");
        assert_eq!(Codec::Cp1252.encode("café"), b"caf\xe9");
    }

    #[test]
    fn a_character_the_page_cannot_hold_becomes_one_question_mark() {
        // One per character, not per byte: this is the length the dbf width check and
        // Python's own `errors="replace"` see.
        assert_eq!(Codec::Cp1252.encode("名前"), b"??");
        assert_eq!(Codec::Ascii.encode("é"), b"?");
        assert_eq!(Codec::Latin1.encode("é"), b"\xe9");
        assert_eq!(Codec::Ascii.encode("é"), b"?");
        // And UTF-8 never substitutes anything: it is the one page that can hold every
        // character a `str` can.
        assert_eq!(Codec::Utf8.encode("café 名前"), "café 名前".as_bytes());
        // Below the high half nothing changes between the single-byte pages, which is
        // what lets them share the ASCII path.
        for codec in Codec::ALL {
            assert_eq!(codec.encode("plain ASCII"), b"plain ASCII", "{codec:?}");
        }
    }

    #[test]
    fn only_the_page_dbase_has_a_code_for_claims_one() {
        // The default is the previous engine's byte, which the golden comparison
        // depends on.
        assert_eq!(Codec::Cp1252.language_driver(), 0x03);
        assert_eq!(Codec::Cp437.language_driver(), 0x01);
        assert_eq!(Codec::Cp850.language_driver(), 0x02);
        // UTF-8 has no dBase code page, and neither has ISO-8859-1. `0x00` is the
        // format's "unknown"; claiming cp1252 for a UTF-8 record is the lie being
        // removed.
        assert_eq!(Codec::Utf8.language_driver(), 0x00);
        assert_eq!(Codec::Latin1.language_driver(), 0x00);
        assert_eq!(Codec::Ascii.language_driver(), 0x00);
    }

    #[test]
    fn a_single_byte_page_writes_at_most_one_byte_per_character() {
        // Which is what makes a code page safe for a fixed-width dbf field: nothing here
        // escapes into something longer, so the byte count of a value is bounded by its
        // character count and the width check cannot be surprised.
        for codec in [
            Codec::Ascii,
            Codec::Latin1,
            Codec::Cp1252,
            Codec::Cp437,
            Codec::Cp850,
        ] {
            for text in ["", "a", "café", "名前", "\u{1F600}", "\u{80}\u{9f}"] {
                assert!(
                    codec.encode(text).len() <= text.chars().count(),
                    "{codec:?} {text:?}"
                );
            }
        }
        // UTF-8 is the one that can grow, by at most four bytes per character.
        for text in ["", "café", "名前", "\u{1F600}"] {
            let encoded = Codec::Utf8.encode(text);
            assert!(encoded.len() <= text.chars().count() * 4, "{text:?}");
            assert_eq!(encoded, text.as_bytes());
        }
    }
}
