//! Integration tests against a real `sshd` in a container.
//!
//! ```bash
//! deploy/dev/qh-sshd-run.sh
//! QH_TEST_SSH=1 cargo test -p qh-tunnel --test sshd
//! ```
//!
//! Without `QH_TEST_SSH=1` every test prints why it is skipping and returns. That is
//! deliberate, the same way the driver integration tests do it: a green run that tested
//! nothing is worse than a visible skip.
//!
//! Why these exist at all, next to the unit tests
//! ----------------------------------------------
//! The unit tests prove the rules of the file format. They cannot prove that the rules
//! meet a real server: a real host key arrives through a key exchange `russh` drives, a
//! real refusal has to stop authentication before a password is sent, and a forwarded
//! byte has to survive a channel. Those are facts about the wire, which is what is
//! checked here.

use std::path::{Path, PathBuf};
use std::time::Duration;

use qh_tunnel::known_hosts::{self, HostKeyVerdict};
use qh_tunnel::{Auth, BastionConfig, Error, SecretString, Target, Tunnel};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpStream;
use tokio::time::timeout;

const SKIP_HINT: &str =
    "skipped: set QH_TEST_SSH=1 with deploy/dev/qh-sshd-run.sh running (container qh-sshd-dev)";

/// How this machine's container is reached. Everything is overridable so the same tests
/// can point at a different sshd, but the defaults are deploy/dev/qh-sshd-run.sh's.
struct Settings {
    host: String,
    port: u16,
    user: String,
    password: String,
    key: PathBuf,
}

impl Settings {
    fn from_env() -> Option<Self> {
        if std::env::var("QH_TEST_SSH").as_deref() != Ok("1") {
            return None;
        }
        let key = std::env::var("QH_SSH_KEY").map_or_else(
            |_| Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/qh-sshd/id_ed25519"),
            PathBuf::from,
        );
        Some(Self {
            host: std::env::var("QH_SSH_HOST").unwrap_or_else(|_| "127.0.0.1".to_owned()),
            port: std::env::var("QH_SSH_PORT")
                .ok()
                .and_then(|port| port.parse().ok())
                .unwrap_or(52222),
            user: std::env::var("QH_SSH_USER").unwrap_or_else(|_| "qh".to_owned()),
            password: std::env::var("QH_SSH_PASSWORD")
                .unwrap_or_else(|_| "qh-sshd-dev-only".to_owned()),
            key,
        })
    }

    /// The bastion as the tunnel sees it: a strict check against `known_hosts`.
    fn bastion(&self, known_hosts: &Path) -> BastionConfig {
        BastionConfig::new(
            self.host.clone(),
            self.port,
            self.user.clone(),
            Auth::Key {
                path: self.key.clone(),
                passphrase: None,
            },
            known_hosts,
        )
    }

    fn password_bastion(&self, known_hosts: &Path) -> BastionConfig {
        BastionConfig::new(
            self.host.clone(),
            self.port,
            self.user.clone(),
            Auth::Password(SecretString::new(self.password.clone().into_boxed_str())),
            known_hosts,
        )
    }
}

/// Skip visibly, then hand back the settings. Every test starts here.
fn settings() -> Option<Settings> {
    match Settings::from_env() {
        Some(settings) => Some(settings),
        None => {
            eprintln!("{SKIP_HINT}");
            None
        }
    }
}

/// A `known_hosts` of our own, so nothing here touches the user's `~/.ssh`.
fn fresh_known_hosts() -> (tempfile::TempDir, PathBuf) {
    let dir = tempfile::tempdir().expect("temp dir");
    let path = dir.path().join("known_hosts");
    (dir, path)
}

/// A real ed25519 key generated by `ssh-keygen`, as its decoded blob: a second host key
/// that is genuinely a different key rather than a hand-written one.
fn generated_ed25519_blob(dir: &Path, name: &str) -> Vec<u8> {
    let path = dir.join(name);
    let status = std::process::Command::new("ssh-keygen")
        .args([
            "-q",
            "-t",
            "ed25519",
            "-N",
            "",
            "-C",
            "qh-tunnel-test",
            "-f",
        ])
        .arg(&path)
        .status()
        .expect("run ssh-keygen");
    assert!(status.success(), "ssh-keygen failed");
    let public = std::fs::read_to_string(path.with_extension("pub")).expect("read the .pub");
    let body = public
        .split_whitespace()
        .nth(1)
        .expect("a .pub has a base64 body");
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD
        .decode(body)
        .expect("the .pub body is base64")
}

/// Connect once with nothing recorded, hand back the key the server presented: this is
/// exactly the situation a person is prompted about.
async fn unknown_host_key(settings: &Settings, known_hosts: &Path) -> qh_tunnel::ServerKey {
    let error =
        match Tunnel::open(&settings.bastion(known_hosts), Target::new("127.0.0.1", 22)).await {
            Err(error) => error,
            Ok(tunnel) => {
                tunnel.close().await;
                panic!("an empty known_hosts was accepted; TOFU accepted a host on its own");
            }
        };
    match error {
        Error::HostKeyUnknown {
            key,
            covered_by_certificate_authority,
            ..
        } => {
            assert!(
                !covered_by_certificate_authority,
                "the container has no @cert-authority line"
            );
            assert!(
                key.fingerprint().starts_with("SHA256:"),
                "the prompt needs a fingerprint"
            );
            key
        }
        other => panic!("expected an unknown host, got {other}"),
    }
}

/// Bring up a tunnel through a known_hosts that already records the container's key.
async fn accepted_tunnel(settings: &Settings, known_hosts: &Path) -> Tunnel {
    let key = unknown_host_key(settings, known_hosts).await;
    known_hosts::append(known_hosts, &settings.host, settings.port, key.blob())
        .expect("append the presented key");
    Tunnel::open(&settings.bastion(known_hosts), Target::new("127.0.0.1", 22))
        .await
        .expect("open with the key recorded")
}

#[tokio::test]
async fn unknown_host_is_reported_with_a_fingerprint_and_matches_once_recorded() {
    let Some(settings) = settings() else { return };
    let (_dir, known_hosts) = fresh_known_hosts();

    // 1. Nothing recorded: the server is reported, not trusted.
    let key = unknown_host_key(&settings, &known_hosts).await;
    eprintln!(
        "{host}:{port} presented {key_type} {fingerprint}",
        host = settings.host,
        port = settings.port,
        key_type = key.key_type(),
        fingerprint = key.fingerprint()
    );

    // The file is untouched: refusing must not be the same as accepting.
    assert!(
        !known_hosts.exists(),
        "a refused host must not be written to known_hosts"
    );

    // 2. The person says yes: recorded, and now the same host matches.
    known_hosts::append(&known_hosts, &settings.host, settings.port, key.blob()).expect("append");
    assert_eq!(
        known_hosts::check(&known_hosts, &settings.host, settings.port, key.blob()).unwrap(),
        HostKeyVerdict::Matched
    );

    // 3. And the tunnel now opens against the real server.
    let tunnel = Tunnel::open(
        &settings.bastion(&known_hosts),
        Target::new("127.0.0.1", 22),
    )
    .await
    .expect("open with the key recorded");
    assert_ne!(tunnel.local_port(), 0);
    tunnel.close().await;
}

#[tokio::test]
async fn a_different_host_key_for_the_same_host_is_a_mismatch() {
    let Some(settings) = settings() else { return };
    let (dir, known_hosts) = fresh_known_hosts();
    let presented = unknown_host_key(&settings, &known_hosts).await;

    // A second, real host key: generated with ssh-keygen and recorded for this host,
    // while the container keeps presenting its own.
    let second = generated_ed25519_blob(dir.path(), "second_host_key");
    known_hosts::append(&known_hosts, &settings.host, settings.port, &second).expect("append");

    match Tunnel::open(
        &settings.bastion(&known_hosts),
        Target::new("127.0.0.1", 22),
    )
    .await
    {
        Err(Error::HostKeyMismatch {
            key,
            recorded,
            path,
            ..
        }) => {
            assert_eq!(path, known_hosts);
            assert_eq!(
                key.blob(),
                presented.blob(),
                "the presented key is reported"
            );
            assert_eq!(recorded.len(), 1);
            assert_ne!(
                recorded[0].fingerprint(),
                key.fingerprint(),
                "a mismatch reports a key that is not the presented one"
            );
        }
        Err(other) => panic!("expected a mismatch, got {other}"),
        Ok(tunnel) => {
            tunnel.close().await;
            panic!("a changed host key was accepted");
        }
    }
}

#[tokio::test]
async fn a_revoked_key_is_refused_and_trust_new_cannot_override_it() {
    let Some(settings) = settings() else { return };
    let (_dir, known_hosts) = fresh_known_hosts();
    let presented = unknown_host_key(&settings, &known_hosts).await;

    // Only a revocation is on record, which is the case that must not read as
    // "unknown, may I add it?".
    std::fs::write(
        &known_hosts,
        format!(
            "@revoked {}\n",
            presented.known_hosts_line(&settings.host, settings.port)
        ),
    )
    .unwrap();

    match Tunnel::open(
        &settings.bastion(&known_hosts),
        Target::new("127.0.0.1", 22),
    )
    .await
    {
        Err(Error::HostKeyRevoked { line, .. }) => assert_eq!(line, 1),
        Err(other) => panic!("expected a revoked refusal, got {other}"),
        Ok(tunnel) => {
            tunnel.close().await;
            panic!("a revoked key was accepted");
        }
    }

    // Trust-on-first-use may never override a revocation, however explicit the answer.
    let trusted = settings.bastion(&known_hosts).trust_new(presented);
    match Tunnel::open(&trusted, Target::new("127.0.0.1", 22)).await {
        Err(Error::HostKeyRevoked { .. }) => {}
        Err(other) => panic!("expected a revoked refusal, got {other}"),
        Ok(tunnel) => {
            tunnel.close().await;
            panic!("trust_new overrode a revocation");
        }
    }
}

#[tokio::test]
async fn trust_new_accepts_the_key_it_was_given_and_no_other() {
    let Some(settings) = settings() else { return };
    let (dir, known_hosts) = fresh_known_hosts();
    let presented = unknown_host_key(&settings, &known_hosts).await;

    // The answer to a prompt, replayed: the file stays empty, the key is accepted.
    let trusted = settings.bastion(&known_hosts).trust_new(presented.clone());
    let tunnel = Tunnel::open(&trusted, Target::new("127.0.0.1", 22))
        .await
        .expect("the approved key is accepted");
    assert_ne!(tunnel.local_port(), 0);
    tunnel.close().await;
    assert!(!known_hosts.exists(), "trust_new does not write the file");

    // A different key in the same policy slot is a mismatch, not a new prompt.
    let wrong = qh_tunnel::ServerKey::from_blob(generated_ed25519_blob(dir.path(), "other_key"))
        .expect("a real key");
    let trusted = settings.bastion(&known_hosts).trust_new(wrong);
    match Tunnel::open(&trusted, Target::new("127.0.0.1", 22)).await {
        Err(Error::HostKeyMismatch { .. }) => {}
        Err(other) => panic!("expected a mismatch, got {other}"),
        Ok(tunnel) => {
            tunnel.close().await;
            panic!("a key that was not approved was accepted");
        }
    }
}

#[tokio::test]
async fn a_forward_carries_bytes_through_the_bastion_in_both_directions() {
    let Some(settings) = settings() else { return };
    let (_dir, known_hosts) = fresh_known_hosts();

    // Forwarded to the container's own sshd, whose greeting is recognisable and whose
    // key exchange starts as soon as we send ours.
    let tunnel = accepted_tunnel(&settings, &known_hosts).await;
    let mut stream = TcpStream::connect(("127.0.0.1", tunnel.local_port()))
        .await
        .expect("connect to the tunnel");

    let mut banner = Vec::new();
    timeout(Duration::from_secs(10), stream.read_buf(&mut banner))
        .await
        .expect("the forwarded server said nothing")
        .expect("read the greeting through the tunnel");
    let banner = String::from_utf8_lossy(&banner).into_owned();
    eprintln!("through the tunnel: {}", banner.trim_end());
    assert!(
        banner.starts_with("SSH-2.0-OpenSSH_"),
        "expected an OpenSSH greeting through the tunnel, got {banner:?}"
    );

    // And the other direction: our own identification line makes the server answer with
    // the binary key exchange, which can only happen if what we wrote arrived.
    stream
        .write_all(b"SSH-2.0-qh-tunnel-test\r\n")
        .await
        .expect("write through the tunnel");
    let mut kex = Vec::new();
    timeout(Duration::from_secs(10), stream.read_buf(&mut kex))
        .await
        .expect("the forwarded server ignored what we sent")
        .expect("read the key exchange through the tunnel");
    assert!(
        !kex.is_empty(),
        "nothing came back after our identification"
    );

    drop(stream);
    tunnel.close().await;
}

#[tokio::test]
async fn password_authentication_reaches_the_same_place() {
    let Some(settings) = settings() else { return };
    let (_dir, known_hosts) = fresh_known_hosts();
    let key = unknown_host_key(&settings, &known_hosts).await;
    known_hosts::append(&known_hosts, &settings.host, settings.port, key.blob()).expect("append");

    let tunnel = Tunnel::open(
        &settings.password_bastion(&known_hosts),
        Target::new("127.0.0.1", 22),
    )
    .await
    .expect("open with a password");
    assert_ne!(tunnel.local_port(), 0);
    tunnel.close().await;
}

#[tokio::test]
async fn a_wrong_password_is_reported_as_a_rejection() {
    let Some(settings) = settings() else { return };
    let (_dir, known_hosts) = fresh_known_hosts();
    let key = unknown_host_key(&settings, &known_hosts).await;
    known_hosts::append(&known_hosts, &settings.host, settings.port, key.blob()).expect("append");

    let mut config = settings.bastion(&known_hosts);
    config.auth = Auth::Password(SecretString::new(
        "not-the-password".to_owned().into_boxed_str(),
    ));
    match Tunnel::open(&config, Target::new("127.0.0.1", 22)).await {
        Err(Error::AuthenticationRejected { user, .. }) => assert_eq!(user, settings.user),
        Err(other) => panic!("expected a rejected authentication, got {other}"),
        Ok(tunnel) => {
            tunnel.close().await;
            panic!("a wrong password authenticated");
        }
    }
}

/// The agent path needs an agent holding a key the container accepts, which this
/// container does not do by default. It is checked when the environment offers one and
/// skipped visibly when it does not.
#[tokio::test]
async fn agent_authentication_is_used_when_an_agent_is_available() {
    let Some(settings) = settings() else { return };
    let agent_available = std::env::var("SSH_AUTH_SOCK").is_ok_and(|socket| !socket.is_empty());
    if !agent_available {
        eprintln!("skipped agent authentication: SSH_AUTH_SOCK is not set or empty");
        return;
    }
    let (_dir, known_hosts) = fresh_known_hosts();
    let key = unknown_host_key(&settings, &known_hosts).await;
    known_hosts::append(&known_hosts, &settings.host, settings.port, key.blob()).expect("append");

    let mut config = settings.bastion(&known_hosts);
    config.auth = Auth::Agent;
    match Tunnel::open(&config, Target::new("127.0.0.1", 22)).await {
        Ok(tunnel) => tunnel.close().await,
        // A sign in the environment that holds no key the container knows is not a
        // failure of this crate, and saying so is better than a false pass.
        Err(Error::AuthenticationRejected { methods, .. }) => {
            eprintln!("agent authentication unused: the agent's keys were refused ({methods})");
        }
        Err(other) => panic!("agent authentication failed unexpectedly: {other}"),
    }
}
